version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "0.2"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "0.2"
    schedule:
      interval: "daily"
